on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Output build artifacts to /github/workspace on the container.
      - name: Execute technical lag calculator
        uses: fraunhofer-iem/technical-lag-action@v0.0.1
        id: techlag
        with:
          inputPath: packageFiles/azurechat
          outputPath: statistics

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: technical_lag_artifacts
          path: ${{ github.workspace }}/statistics
